.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-confirm \-


.SH SYNOPSIS
.PP
\fBjrctl confirm [flags]\fP


.SH DESCRIPTION
.PP
\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for confirm

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible


.SH EXAMPLE
.PP
.RS

.nf
jrctl confirm e01b1e47\-c12d\-453f\-9905\-d25fcc6c3eed
echo e01b1e47\-c12d\-453f\-9905\-d25fcc6c3eed | jrctl confirm

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP
