.nh
.TH "JetRails CLI" "1" "Apr 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-report \- Generate server reports


.SH SYNOPSIS
.PP
\fBjrctl report [flags]\fP


.SH DESCRIPTION
.PP
Generate server reports


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for report


.SH EXAMPLE
.PP
.RS

.nf
jrctl report audit \-h

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-report\-audit(1)\fP
