.nh
.TH "JetRails CLI" "1" "May 2025" "Copyright 2025 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-user\-delete \- Delete database user


.SH SYNOPSIS
.PP
\fBjrctl database user delete USER@HOST [flags]\fP


.SH DESCRIPTION
.PP
Delete database user


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for delete

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display confirmation code

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH SEE ALSO
.PP
\fBjrctl\-database\-user(1)\fP
