.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-unlink \- Remove database user to specific database


.SH SYNOPSIS
.PP
\fBjrctl database unlink USER@FROM DB\_NAME [flags]\fP


.SH DESCRIPTION
.PP
Remove database user to specific database


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for unlink

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display confirmation code

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
