.nh
.TH "JetRails CLI" "1" "Jun 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl \- Command line tool to help interact with the >jetrails\_ API.


.SH SYNOPSIS
.PP
\fBjrctl [flags]\fP


.SH DESCRIPTION
.PP
Command line tool to help interact with the >jetrails\_ API. Hosted on Github,
https://github.com/jetrails/jrctl. For issues/requests, please open an issue in
our Github repository.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for jrctl


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP, \fBjrctl\-firewall(1)\fP, \fBjrctl\-report(1)\fP, \fBjrctl\-secret(1)\fP, \fBjrctl\-server(1)\fP, \fBjrctl\-service(1)\fP, \fBjrctl\-update(1)\fP, \fBjrctl\-utility(1)\fP, \fBjrctl\-version(1)\fP, \fBjrctl\-website(1)\fP
