.nh
.TH "JetRails CLI" "1" "Nov 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-transfer\-send \- Upload file to secure server


.SH SYNOPSIS
.PP
\fBjrctl transfer send [flags]\fP


.SH DESCRIPTION
.PP
Upload file to secure server. File is encrypted and stored for an hour.


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-clipboard\fP[=false]
	copy file identifier to clipboard

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for send

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible


.SH EXAMPLE
.PP
.RS

.nf
jrctl transfer send private.png

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-transfer(1)\fP
