.nh
.TH "JetRails CLI" "1" "Dec 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-website \- Manage websites in deployment


.SH SYNOPSIS
.PP
\fBjrctl website [flags]\fP


.SH DESCRIPTION
.PP
Manage websites in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for website


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-website\-list(1)\fP, \fBjrctl\-website\-php\-available(1)\fP, \fBjrctl\-website\-php\-switch(1)\fP
