.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-daemon\-version \- Display version of configured daemons


.SH SYNOPSIS
.PP
\fBjrctl daemon version [flags]\fP


.SH DESCRIPTION
.PP
Display version of configured daemons.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for version

.PP
\fB\-t\fP, \fB\-\-tag\fP=""
	specify daemon tag selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl daemon version

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-daemon(1)\fP
