.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-node\-list \- Displays token information for all configured nodes


.SH SYNOPSIS
.PP
\fBjrctl node list [flags]\fP


.SH DESCRIPTION
.PP
Displays token information for all configured nodes.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-i\fP, \fB\-\-identity\fP=[]
	filter with identity

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display versions

.PP
\fB\-t\fP, \fB\-\-tag\fP=[]
	filter nodes using tags

.PP
\fB\-I\fP, \fB\-\-token\-id\fP=[]
	filter with token id


.SH EXAMPLE
.PP
.RS

.nf
jrctl node token

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-node(1)\fP
