.nh
.TH "JetRails CLI" "1" "Aug 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database \- Manage databases in deployment


.SH SYNOPSIS
.PP
\fBjrctl database [flags]\fP


.SH DESCRIPTION
.PP
Manage databases in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for database


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-database\-create(1)\fP, \fBjrctl\-database\-delete(1)\fP, \fBjrctl\-database\-link(1)\fP, \fBjrctl\-database\-list(1)\fP, \fBjrctl\-database\-unlink(1)\fP, \fBjrctl\-database\-user(1)\fP
