.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server\-list \- List configured servers


.SH SYNOPSIS
.PP
\fBjrctl server list [flags]\fP


.SH DESCRIPTION
.PP
List configured servers.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-t\fP, \fB\-\-type\fP=""
	specify server type selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl server list
jrctl server list \-t www

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-server(1)\fP
