.nh
.TH "JetRails CLI" "1" "Jul 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret\-read \- Display contents of secret


.SH SYNOPSIS
.PP
\fBjrctl secret read IDENTIFIER [flags]\fP


.SH DESCRIPTION
.PP
Display contents of secret. Passing the secret identifier will allow us to
retrieve the contents of the secret and print it to STDOUT. Optionally, you can
copy the contents to your clipboard by passing the \-\-clipboard flag! If the
secret's URL is passed, the identifier is extracted automatically.


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-clipboard\fP[=false]
	copy contents to clipboard

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for read

.PP
\fB\-p\fP, \fB\-\-password\fP=""
	password to access secret


.SH EXAMPLE
.PP
.RS

.nf
jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq
jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq \-c
jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq \-c \-p secretpass
echo 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq | jrctl secret read

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-secret(1)\fP
