.nh
.TH "JetRails CLI" "1" "Feb 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-update \- Check to see if there is an update available


.SH SYNOPSIS
.PP
\fBjrctl update [flags]\fP


.SH DESCRIPTION
.PP
Check to see if there is an update available


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update


.SH EXAMPLE
.PP
.RS

.nf
jrctl server update

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP
