.nh
.TH "JetRails CLI" "1" "Jun 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-utility \- Auxiliary command\-line tools


.SH SYNOPSIS
.PP
\fBjrctl utility [flags]\fP


.SH DESCRIPTION
.PP
Auxiliary command\-line tools


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for utility


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-utility\-mkpass(1)\fP
