.nh
.TH "JetRails CLI" "1" "Apr 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server\-restart \- Restart specified service(s) running on configured server(s)


.SH SYNOPSIS
.PP
\fBjrctl server restart SERVICE... [flags]\fP


.SH DESCRIPTION
.PP
Restart specified service(s) running on configured server(s). In order to
successfully restart a service, the server first validates the respected
service's config file. Once deemed valid, the service is restarted. For a list
of available running services, run 'jrctl server list'. Services can be repeated
and execution will happen in the order that is given. Specifing a server type
will only display results for servers of that type.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for restart

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible

.PP
\fB\-t\fP, \fB\-\-type\fP="localhost"
	specify server type, useful for cluster


.SH EXAMPLE
.PP
.RS

.nf
jrctl server restart nginx
jrctl server restart nginx varnish
jrctl server restart nginx varnish php\-fpm
jrctl server restart nginx varnish php\-fpm\-7.2 nginx

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-server(1)\fP
