.nh
.TH "JetRails CLI" "1" "Feb 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret \- Interact with our one\-time secret service


.SH SYNOPSIS
.PP
\fBjrctl secret [flags]\fP


.SH DESCRIPTION
.PP
Interact with our one\-time secret service


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for secret


.SH EXAMPLE
.PP
.RS

.nf
  jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq
  jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq \-c
  jrctl secret read 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq \-c \-p secretpass
  jrctl secret delete 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq
  jrctl secret create
  jrctl secret create \-c \-a
  jrctl secret create \-c \-t 60
  jrctl secret create \-c \-p secretpass
  jrctl secret create \-c \-f \~/.ssh/id\_rsa.pub

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-secret\-create(1)\fP, \fBjrctl\-secret\-delete(1)\fP, \fBjrctl\-secret\-read(1)\fP
