.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-link \- Add database user to specific database


.SH SYNOPSIS
.PP
\fBjrctl database link USER@FROM DB\_NAME [flags]\fP


.SH DESCRIPTION
.PP
Add database user to specific database


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for link

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no output

.PP
\fB\-t\fP, \fB\-\-type\fP=[localhost]
	filter servers using type selectors


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
