.nh
.TH "JetRails CLI" "1" "Jun 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-node\-version \- Display daemon version running on configured nodes


.SH SYNOPSIS
.PP
\fBjrctl node version [flags]\fP


.SH DESCRIPTION
.PP
Display daemon version running on configured nodes. Specifing a node type will
only display results for nodes of that type.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for version

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display versions

.PP
\fB\-t\fP, \fB\-\-tag\fP=[]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
jrctl node version
jrctl node version \-t www

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-node(1)\fP
