.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service\-restart \- Restart apache, nginx, mysql, or varnish service


.SH SYNOPSIS
.PP
\fBjrctl service restart SERVICE [flags]\fP


.SH DESCRIPTION
.PP
Restart apache, nginx, mysql, or varnish service. Ask the daemon to restart a
given service. In order to successfully restart it, the daemon first validates
the respected service's configuration.

.PP
The following environmental variables can be passed in place of the 'endpoint'
and 'token' flags: JR\_DAEMON\_ENDPOINT, JR\_DAEMON\_TOKEN.


.SH OPTIONS
.PP
\fB\-e\fP, \fB\-\-endpoint\fP="localhost:27482"
	specify endpoint hostname

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for restart

.PP
\fB\-t\fP, \fB\-\-token\fP=""
	specify auth token


.SH EXAMPLE
.PP
.RS

.nf
jrctl service restart apache
jrctl service restart nginx
jrctl service restart mysql
jrctl service restart varnish

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-service(1)\fP
