.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service\-list \- List available services


.SH SYNOPSIS
.PP
\fBjrctl service list [flags]\fP


.SH DESCRIPTION
.PP
List available services.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-t\fP, \fB\-\-type\fP=""
	specify service type selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl service list
jrctl service list \-t www

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-service(1)\fP
