.nh
.TH "JetRails CLI" "1" "Jun 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-user\-list \- Display database users in deployment


.SH SYNOPSIS
.PP
\fBjrctl database user list [flags]\fP


.SH DESCRIPTION
.PP
Display database users in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display database user names

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	specify tag, useful for cluster


.SH SEE ALSO
.PP
\fBjrctl\-database\-user(1)\fP
