.nh
.TH "JetRails CLI" "1" "Apr 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-transfer\-receive \- Download file from secure server


.SH SYNOPSIS
.PP
\fBjrctl transfer receive [flags]\fP


.SH DESCRIPTION
.PP
Download file from secure server.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	force download, overwrite existing file

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for receive

.PP
\fB\-n\fP, \fB\-\-name\fP=""
	specify file name

.PP
\fB\-o\fP, \fB\-\-out\-dir\fP=""
	specify download directory, default $PWD

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible


.SH EXAMPLE
.PP
.RS

.nf
jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo
jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo \-f
jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo \-o ./private/
jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo \-n custom.name
jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo \-o ./private/ \-n custom.name
echo 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo | jrctl transfer receive

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-transfer(1)\fP
