.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-unallow\-cloudflare \- Remove allow entries for Cloudflare IP addresses


.SH SYNOPSIS
.PP
\fBjrctl firewall unallow cloudflare [flags]\fP


.SH DESCRIPTION
.PP
Remove allow entries for Cloudflare IP addresses.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for cloudflare

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no output

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
jrctl firewall unallow cloudflare
jrctl firewall unallow cloudflare \-t www

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall\-unallow(1)\fP
