.nh
.TH "JetRails CLI" "1" "Sep 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-version \- Display current version


.SH SYNOPSIS
.PP
\fBjrctl version [flags]\fP


.SH DESCRIPTION
.PP
Display current version


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for version

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	be quiet, very quiet


.SH EXAMPLE
.PP
.RS

.nf
jrctl version
jrctl version \-q

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP
