.nh
.TH "JetRails CLI" "1" "Nov 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret\-delete \- Delete secret without viewing contents


.SH SYNOPSIS
.PP
\fBjrctl secret delete IDENTIFIER [flags]\fP


.SH DESCRIPTION
.PP
Delete secret without viewing contents. Passing the secret identifier will make
a request to destroy the secret without displaying the secret's contents. If the
secret's URL is passed, the identifier is extracted automatically.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for delete

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible


.SH EXAMPLE
.PP
.RS

.nf
jrctl secret delete 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq
echo 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq | jrctl secret delete

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-secret(1)\fP
