.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-daemon \- Interact with configured daemons


.SH SYNOPSIS
.PP
\fBjrctl daemon [flags]\fP


.SH DESCRIPTION
.PP
Interact with configured daemons


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for daemon


.SH EXAMPLE
.PP
.RS

.nf
jrctl daemon list \-h
jrctl daemon version \-h

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-daemon\-list(1)\fP, \fBjrctl\-daemon\-version(1)\fP
