.nh
.TH "JetRails CLI" "1" "Jun 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server \- Manage servers in deployment


.SH SYNOPSIS
.PP
\fBjrctl server [flags]\fP


.SH DESCRIPTION
.PP
Manage servers in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for server


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-server\-ingest(1)\fP, \fBjrctl\-server\-list(1)\fP, \fBjrctl\-server\-version(1)\fP
