.nh
.TH "JetRails CLI" "1" "Apr 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server \- Interact with servers in configured deployment


.SH SYNOPSIS
.PP
\fBjrctl server [flags]\fP


.SH DESCRIPTION
.PP
Interact with servers in configured deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for server


.SH EXAMPLE
.PP
.RS

.nf
  jrctl server list \-h
  jrctl server restart \-h
  jrctl server version \-h

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-server\-ingest(1)\fP, \fBjrctl\-server\-list(1)\fP, \fBjrctl\-server\-restart(1)\fP, \fBjrctl\-server\-version(1)\fP
