.nh
.TH "JetRails CLI" "1" "Oct 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret \- Interact with one\-time secret service


.SH SYNOPSIS
.PP
\fBjrctl secret [flags]\fP


.SH DESCRIPTION
.PP
Interact with one\-time secret service


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for secret


.SH EXAMPLE
.PP
.RS

.nf
jrctl secret create \-h
jrctl secret delete \-h
jrctl secret read \-h

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-secret\-create(1)\fP, \fBjrctl\-secret\-delete(1)\fP, \fBjrctl\-secret\-read(1)\fP
