.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-allow \- Add entry to firewall


.SH SYNOPSIS
.PP
\fBjrctl firewall allow [flags]\fP


.SH DESCRIPTION
.PP
Add entry to firewall. Ask the daemon to create an allow entry in the system's
firewall.

.PP
The following environmental variables can be passed in place of the 'endpoint'
and 'token' flags: JR\_DAEMON\_ENDPOINT, JR\_DAEMON\_TOKEN.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-address\fP=""
	IP address to firewall

.PP
\fB\-b\fP, \fB\-\-blame\fP="raffi"
	specify blame entry

.PP
\fB\-c\fP, \fB\-\-comment\fP="none"
	add optional comment

.PP
\fB\-e\fP, \fB\-\-endpoint\fP="localhost:27482"
	specify endpoint hostname

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for allow

.PP
\fB\-p\fP, \fB\-\-port\fP=[]
	port(s) to firewall

.PP
\fB\-t\fP, \fB\-\-token\fP=""
	specify auth token


.SH EXAMPLE
.PP
.RS

.nf
jrctl firewall allow \-a 1.1.1.1 \-p 80 \-p 443
jrctl firewall allow \-a 1.1.1.1 \-p 80,443 \-b me
jrctl firewall allow \-a 1.1.1.1 \-p 80,443 \-b me \-c 'Office'

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
