.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall \- Interact with firewall to whitelist IP addresses/ports


.SH SYNOPSIS
.PP
\fBjrctl firewall [flags]\fP


.SH DESCRIPTION
.PP
Interact with firewall to whitelist IP addresses/ports


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for firewall


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-firewall\-allow(1)\fP, \fBjrctl\-firewall\-deny(1)\fP, \fBjrctl\-firewall\-list(1)\fP, \fBjrctl\-firewall\-unallow(1)\fP, \fBjrctl\-firewall\-undeny(1)\fP
