.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-daemon\-list \- List configured daemons


.SH SYNOPSIS
.PP
\fBjrctl daemon list [flags]\fP


.SH DESCRIPTION
.PP
List configured daemons.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-t\fP, \fB\-\-type\fP=""
	specify daemon type selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl daemon list
jrctl daemon list \-t web

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-daemon(1)\fP
