.nh
.TH "JetRails CLI" "1" "Jun 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-node \- Manage configured nodes


.SH SYNOPSIS
.PP
\fBjrctl node [flags]\fP


.SH DESCRIPTION
.PP
Manage configured nodes


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for node


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-node\-delete(1)\fP, \fBjrctl\-node\-ingest(1)\fP, \fBjrctl\-node\-list(1)\fP, \fBjrctl\-node\-version(1)\fP
