.nh
.TH "JetRails CLI" "1" "Dec 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-user \- Manage database users in deployment


.SH SYNOPSIS
.PP
\fBjrctl database user [flags]\fP


.SH DESCRIPTION
.PP
Manage database users in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for user


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP, \fBjrctl\-database\-user\-create(1)\fP, \fBjrctl\-database\-user\-delete(1)\fP, \fBjrctl\-database\-user\-list(1)\fP, \fBjrctl\-database\-user\-password(1)\fP
