.nh
.TH "JetRails CLI" "1" "Jul 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service \- Interact with services in deployment


.SH SYNOPSIS
.PP
\fBjrctl service [flags]\fP


.SH DESCRIPTION
.PP
Interact with services in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for service


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-service\-disable(1)\fP, \fBjrctl\-service\-enable(1)\fP, \fBjrctl\-service\-list(1)\fP, \fBjrctl\-service\-reload(1)\fP, \fBjrctl\-service\-restart(1)\fP
