.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-delete \- Delete a database


.SH SYNOPSIS
.PP
\fBjrctl database delete DB\_NAME [flags]\fP


.SH DESCRIPTION
.PP
Delete a database


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for delete

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display confirmation code

.PP
\fB\-t\fP, \fB\-\-tag\fP=[localhost]
	filter nodes using tags


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
