.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-allow \- Add entry to firewall


.SH SYNOPSIS
.PP
\fBjrctl firewall allow [flags]\fP


.SH DESCRIPTION
.PP
Add entry to firewall. Ask the daemon(s) to create an allow entry to their host
system's firewall.


.SH OPTIONS
.PP
\fB\-t\fP, \fB\-\-tag\fP=""
	Specify deamon tag selector

.PP
\fB\-a\fP, \fB\-\-address\fP=""
	IP address to firewall

.PP
\fB\-p\fP, \fB\-\-port\fP=[]
	port(s) to firewall

.PP
\fB\-c\fP, \fB\-\-comment\fP="none"
	add optional comment

.PP
\fB\-b\fP, \fB\-\-blame\fP="raffi"
	specify blame entry

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for allow


.SH EXAMPLE
.PP
.RS

.nf
jrctl firewall allow \-t nginx \-a 1.1.1.1 \-p 80 \-p 443
jrctl firewall allow \-t admin \-a 1.1.1.1 \-p 22 \-b me
jrctl firewall allow \-t mysql \-a 1.1.1.1 \-p 3306 \-b me \-c 'Office'

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
