.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-unallow \- Deletes allow entry given a source IP address and a port number


.SH SYNOPSIS
.PP
\fBjrctl firewall unallow [flags]\fP


.SH DESCRIPTION
.PP
Removes a 'allow' entry. Able to control a single node as well as cluster of
nodes.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-address\fP=""
	ip address

.PP
\fB\-f\fP, \fB\-\-file\fP=""
	use text file with line separated ips

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for unallow

.PP
\fB\-p\fP, \fB\-\-port\fP=[]
	port to unallow, can be specified multiple times

.PP
\fB\-\-protocol\fP="tcp"
	specify 'tcp' or 'udp', default is 'tcp'

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no input

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
# Stand\-Alone Server
jrctl firewall unallow \-a 1.1.1.1 \-p 22

# Multi\-Server Cluster
jrctl firewall unallow \-t db \-a 1.1.1.1 \-p 3306
jrctl firewall unallow \-t admin \-a 1.1.1.1 \-p 22
jrctl firewall unallow \-t admin \-a 1.1.1.1 \-p 80,443

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP, \fBjrctl\-firewall\-unallow\-cloudflare(1)\fP
