.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service \- Interact with system services


.SH SYNOPSIS
.PP
\fBjrctl service [flags]\fP


.SH DESCRIPTION
.PP
Interact with system services


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for service


.SH EXAMPLE
.PP
.RS

.nf
jrctl service restart \-h

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-service\-restart(1)\fP
