.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-list \- List firewall entries


.SH SYNOPSIS
.PP
\fBjrctl firewall list [flags]\fP


.SH DESCRIPTION
.PP
List firewall entries. Ask daemon(s) for a list of firewall entries. Specifing a
tag selector will only query daemons with that tag. Not specifing any tag will
show query all configured daemons.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-t\fP, \fB\-\-tag\fP=""
	specify daemon tag selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl firewall list
jrctl firewall list \-t admin
jrctl firewall list \-t mysql

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
