.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-report \- Generate reports for deployment


.SH SYNOPSIS
.PP
\fBjrctl report [flags]\fP


.SH DESCRIPTION
.PP
Generate reports for deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for report


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-report\-audit(1)\fP
