.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-user\-password \- Roll database user's password


.SH SYNOPSIS
.PP
\fBjrctl database user password USER@HOST [flags]\fP


.SH DESCRIPTION
.PP
\&.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for password

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display confirmation code

.PP
\fB\-t\fP, \fB\-\-type\fP=[localhost]
	filter servers using type selectors


.SH SEE ALSO
.PP
\fBjrctl\-database\-user(1)\fP
