.nh
.TH "JetRails CLI" "1" "Jun 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service\-restart \- Restart specified services in deployment


.SH SYNOPSIS
.PP
\fBjrctl service restart SERVICE... [flags]\fP


.SH DESCRIPTION
.PP
Restart specified services in deployment. In order to successfully restart a
service, the server first validates the respected service's config file. Once
deemed valid, the service is restarted. Services can be repeated and execution
will happen in the order that is given. Specifing a tag will display nodes that
have that tag.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for restart

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no output

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
jrctl service restart nginx
jrctl service restart nginx varnish
jrctl service restart nginx varnish php\-fpm
jrctl service restart nginx varnish php\-fpm\-7.2 nginx

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-service(1)\fP
