.nh
.TH "JetRails CLI" "1" "Feb 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-list \- List firewall firewall entries


.SH SYNOPSIS
.PP
\fBjrctl firewall list [flags]\fP


.SH DESCRIPTION
.PP
List firewall firewall entries


.SH OPTIONS
.PP
\fB\-e\fP, \fB\-\-endpoint\fP="localhost:27482"
	specify endpoint hostname

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-t\fP, \fB\-\-token\fP=""
	specify auth token


.SH EXAMPLE
.PP
.RS

.nf
  jrctl firewall list

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
