.nh
.TH JetRails Daemon(1)Feb 2021
Copyright 2021 ADF, Inc. All Rights Reserved

.SH NAME
.PP
jrctl \- Command line tool to help interact with the [32m>[0mjetrails[32m\_[0m API


.SH SYNOPSIS
.PP
\fBjrctl [flags]\fP


.SH DESCRIPTION
.PP
Command line tool to help interact with the [32m>[0mjetrails[32m\_[0m API
Hosted on Github, [32mhttps://github.com/jetrails/jrctl[0m.
For issues/requests, please open an issue in our Github repository.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for jrctl


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP, \fBjrctl\-secret(1)\fP
