.nh
.TH "JetRails CLI" "1" "Jun 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-alternative \- Manage alternative programs


.SH SYNOPSIS
.PP
\fBjrctl alternative [flags]\fP


.SH DESCRIPTION
.PP
Manage alternative programs


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for alternative


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-alternative\-list(1)\fP, \fBjrctl\-alternative\-switch(1)\fP
