.nh
.TH "JetRails CLI" "1" "Apr 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-transfer \- Securely transfer files from one machine to another


.SH SYNOPSIS
.PP
\fBjrctl transfer [flags]\fP


.SH DESCRIPTION
.PP
Securely transfer files from one machine to another


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for transfer


.SH EXAMPLE
.PP
.RS

.nf
  jrctl transfer send private.png
  jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo
  jrctl transfer receive 7c6acde6\-639c\-47fe\-8ebb\-a4ac877ef72b\-XPlEYzcsgnNbxwcFqKiWUoJil6MlFXGo \-o private.png

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-transfer\-receive(1)\fP, \fBjrctl\-transfer\-send(1)\fP
