.nh
.TH "JetRails CLI" "1" "Mar 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-list \- List firewall entries


.SH SYNOPSIS
.PP
\fBjrctl firewall list [flags]\fP


.SH DESCRIPTION
.PP
List firewall entries. Ask the daemon for a list of firewall entries. Specifing
the service will only return results with that service. Not specifing any
service will show everything available.


.SH OPTIONS
.PP
\fB\-s\fP, \fB\-\-service\fP=""
	filter by service

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list


.SH EXAMPLE
.PP
.RS

.nf
jrctl firewall list
jrctl firewall list \-s admin
jrctl firewall list \-s mysql

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
