.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-list \- Display databases in deployment


.SH SYNOPSIS
.PP
\fBjrctl database list [flags]\fP


.SH DESCRIPTION
.PP
Display databases in deployment


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	only display database names

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
jrctl database list
jrctl database list \-q
jrctl database list \-t db

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
