.nh
.TH "JetRails CLI" "1" "Apr 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-firewall\-deny \- Permanently denies a source IP address to a specific port


.SH SYNOPSIS
.PP
\fBjrctl firewall deny [flags]\fP


.SH DESCRIPTION
.PP
Denies a specified IP address to bypass the local system firewall by creating an
'deny' entry into the permanent firewall config. Grants unprivileged users
ability to manipulate the firewall in a safe and controlled manner and keeps an
audit log. Able to control a single (localhost) server as well as cluster of
servers.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-address\fP=""
	ip address

.PP
\fB\-c\fP, \fB\-\-comment\fP=""
	add a comment to the firewall entry (optional)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for deny

.PP
\fB\-p\fP, \fB\-\-port\fP=[]
	port to deny, can be specified multiple times

.PP
\fB\-\-protocol\fP="tcp"
	specify 'tcp' or 'udp', default is 'tcp'

.PP
\fB\-t\fP, \fB\-\-type\fP="localhost"
	specify server type, useful for cluster


.SH EXAMPLE
.PP
.RS

.nf
# Stand\-Alone Server
jrctl firewall deny \-a 1.1.1.1 \-p 80 \-p 443

# Multi\-Server Cluster
jrctl firewall deny \-t db \-a 1.1.1.1 \-p 3306
jrctl firewall deny \-t admin \-a 1.1.1.1 \-p 22 \-c 'Office'

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-firewall(1)\fP
