.nh
.TH "JetRails CLI" "1" "Dec 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server\-version \- Display daemon version running on configured servers


.SH SYNOPSIS
.PP
\fBjrctl server version [flags]\fP


.SH DESCRIPTION
.PP
Display daemon version running on configured servers. Specifing a server type
will only display results for servers of that type.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for version

.PP
\fB\-t\fP, \fB\-\-type\fP=""
	specify server type selector


.SH EXAMPLE
.PP
.RS

.nf
jrctl server version

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-server(1)\fP
