.nh
.TH "JetRails CLI" "1" "May 2025" "Copyright 2025 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret \- Interact with one\-time secret service


.SH SYNOPSIS
.PP
\fBjrctl secret [flags]\fP


.SH DESCRIPTION
.PP
Interact with one\-time secret service


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for secret


.SH SEE ALSO
.PP
\fBjrctl(1)\fP, \fBjrctl\-secret\-create(1)\fP, \fBjrctl\-secret\-delete(1)\fP, \fBjrctl\-secret\-read(1)\fP
