.nh
.TH "JetRails CLI" "1" "May 2025" "Copyright 2025 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-service\-list \- List services with their statuses and abilities.


.SH SYNOPSIS
.PP
\fBjrctl service list [flags]\fP


.SH DESCRIPTION
.PP
List services with their statuses and abilities.. Specifing a tag will display
nodes that have that tag. Specifing the service will filter the list of services
to include those services.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display unique list of found services

.PP
\fB\-s\fP, \fB\-\-service\fP=[]
	filter by service

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH EXAMPLE
.PP
.RS

.nf
jrctl service list
jrctl service list \-t admin
jrctl service list \-t default
jrctl service list \-t www

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-service(1)\fP
