.nh
.TH "JetRails CLI" "1" "Aug 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server\-ingest \- Ingest server token and save it to config


.SH SYNOPSIS
.PP
\fBjrctl server ingest [flags]\fP


.SH DESCRIPTION
.PP
Ingest server token and save it to config


.SH OPTIONS
.PP
\fB\-e\fP, \fB\-\-endpoint\fP="127.0.0.1:27482"
	server endpoint used for new entries only

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	create new entry even if matching entries exist

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for ingest

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output only errors

.PP
\fB\-t\fP, \fB\-\-type\fP=[]
	filter servers using type selectors, all must match


.SH EXAMPLE
.PP
.RS

.nf
echo \-n TOKEN | jrctl server ingest \-t localhost
echo \-n TOKEN | jrctl server ingest \-t jump \-e 10.10.10.7
echo \-n TOKEN | jrctl server ingest \-t web \-e 10.10.10.6 \-f

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-server(1)\fP
