.nh
.TH "JetRails CLI" "1" "Dec 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-server\-token \- Displays token information for all configured servers


.SH SYNOPSIS
.PP
\fBjrctl server token [flags]\fP


.SH DESCRIPTION
.PP
Displays token information for all configured servers.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for token

.PP
\fB\-i\fP, \fB\-\-identity\fP=""
	filter with identity, optional

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible

.PP
\fB\-I\fP, \fB\-\-token\-id\fP=""
	filter with token id, optional

.PP
\fB\-t\fP, \fB\-\-type\fP=""
	specify server type selector, optional


.SH EXAMPLE
.PP
.RS

.nf
jrctl server token

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-server(1)\fP
