.nh
.TH "JetRails CLI" "1" "Jul 2021" "Copyright 2021 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-secret\-create \- Create a new one\-time secret


.SH SYNOPSIS
.PP
\fBjrctl secret create [flags]\fP


.SH DESCRIPTION
.PP
Create a new one\-time secret. A secret's content can be populated by passing a
filepath, or it can be manually specified through STDIN. Optionally, the
secret's url can be copied to your clipboard by passing the \-\-clipboard flag!


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-auto\-generate\fP[=false]
	automatically generate password

.PP
\fB\-c\fP, \fB\-\-clipboard\fP[=false]
	copy secret url to clipboard

.PP
\fB\-f\fP, \fB\-\-file\fP=""
	use file contents as secret data

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for create

.PP
\fB\-p\fP, \fB\-\-password\fP=""
	protect secret with a password

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible

.PP
\fB\-t\fP, \fB\-\-ttl\fP=86400
	specify custom ttl in seconds


.SH EXAMPLE
.PP
.RS

.nf
jrctl secret create
jrctl secret create \-c \-a
jrctl secret create \-c \-t 60
jrctl secret create \-c \-p secretpass
jrctl secret create \-c \-f \~/.ssh/id\_rsa.pub
echo 'Hello World' | jrctl secret create

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-secret(1)\fP
