.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-update \- Check for available updates


.SH SYNOPSIS
.PP
\fBjrctl update [flags]\fP


.SH DESCRIPTION
.PP
Check for available updates


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no output


.SH EXAMPLE
.PP
.RS

.nf
jrctl update

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl(1)\fP
