.nh
.TH "JetRails CLI" "1" "May 2022" "Copyright 2022 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-user\-add \-


.SH SYNOPSIS
.PP
\fBjrctl database user\-add USER\_NAME [flags]\fP


.SH DESCRIPTION
.PP
\&.


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-database\fP=""
	specify database to add user to

.PP
\fB\-f\fP, \fB\-\-from\fP="localhost"
	specify host user will be connecting from, [localhost,anywhere,]

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for user\-add

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	output as little information as possible

.PP
\fB\-t\fP, \fB\-\-type\fP=[localhost]
	specify server type, useful for cluster


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
