.nh
.TH "JetRails CLI" "1" "Mar 2023" "Copyright 2023 ADF, Inc. All Rights Reserved " ""

.SH NAME
.PP
jrctl\-database\-create \- Create a database


.SH SYNOPSIS
.PP
\fBjrctl database create DB\_NAME [flags]\fP


.SH DESCRIPTION
.PP
Create a database


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for create

.PP
\fB\-q\fP, \fB\-\-quiet\fP[=false]
	display no output

.PP
\fB\-t\fP, \fB\-\-tag\fP=[default]
	filter nodes using tags


.SH SEE ALSO
.PP
\fBjrctl\-database(1)\fP
