.nh
.TH JetRails Daemon(1)Feb 2021
Copyright 2021 ADF, Inc. All Rights Reserved

.SH NAME
.PP
jrctl\-secret\-delete \- Delete secret without viewing contents


.SH SYNOPSIS
.PP
\fBjrctl secret delete  [flags]\fP


.SH DESCRIPTION
.PP
Delete secret without viewing contents


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for delete


.SH EXAMPLE
.PP
.RS

.nf
  jrctl secret delete 89ea32e9\-e8a5\-435d\-97ce\-78804be250b7\-IUQhHYRq

.fi
.RE


.SH SEE ALSO
.PP
\fBjrctl\-secret(1)\fP
